{% set name = "clickhouse" %}
{% set version = "24.8.5.115" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.memfault1

source:
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-lts/clickhouse-macos # [osx and x86_64]
    sha256: f2b90c95b52a9184e2ae39ca8b5be56cdefaea0ffe3c13fa81d916d828c1758d # [osx and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-lts/clickhouse-macos-aarch64 # [osx and arm64]
    sha256: 3354d8f58f87bb9182c75ad6c4d71d8da97fd16b16449f7a61988d2b44640686 # [osx and arm64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-lts/clickhouse-common-static-{{ version }}-amd64.tgz # [linux64]
    sha256: dae03e7ade008470bf764e5f7d8a1d657ba1c8b9f62230d7afcbe3d03576169a # [linux64]

build:
  number: 0
  binary_relocation: False

test:
  commands:
    - clickhouse client --version

about:
  home: https://clickhouse.com/
  license: Apache 2.0
  summary: ClickHouse® is a free analytics DBMS for big data
  description: |
    ClickHouse® is an open-source column-oriented database management system
    that allows generating analytical data reports in real-time.
  doc_url: https://clickhouse.com/docs
  dev_url: https://github.com/ClickHouse/ClickHouse
