{% set name = "clickhouse" %}
{% set version = "26.4.5.143" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.memfault1

source:
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos # [osx and x86_64]
    sha256: f26411e54653f5bb56665cd508dd3bc21a91c3ef4b6e2838989d36c715b7c9ec # [osx and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos-aarch64 # [osx and arm64]
    sha256: 4e0024bafccc8cf4c6478e6b54182ae55bfaf918e35f9b0fbd48f5c14dc6347c # [osx and arm64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-common-static-{{ version }}-amd64.tgz # [linux and x86_64]
    sha256: 53fca67fdaaee48c6ced5cdcfd3fbd1e016eff66c9b70af4e3993e630d32a57d # [linux and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-common-static-{{ version }}-arm64.tgz # [linux and aarch64]
    sha256: d0b01d1247c25fd607a61610137227d095481f5e68559bd88f2cb3a5b9c490c8 # [linux and aarch64]

build:
  number: 0
  binary_relocation: False

test:
  commands:
    - clickhouse client --version

about:
  home: https://clickhouse.com/
  license: Apache 2.0
  summary: ClickHouse® is a free analytics DBMS for big data
  description: |
    ClickHouse® is an open-source column-oriented database management system
    that allows generating analytical data reports in real-time.
  doc_url: https://clickhouse.com/docs
  dev_url: https://github.com/ClickHouse/ClickHouse
