{% set name = "clickhouse" %}
{% set version = "26.2.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.memfault1

source:
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos # [osx and x86_64]
    sha256: a41399e1d0377ec1a356e43a36ccf6e4e970598231ae0c24dc5e4096813a3fe1 # [osx and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos-aarch64 # [osx and arm64]
    sha256: 3108b8a30a5b2321e4e70a3f7d9ba11f9f3e95d6a5ad5bbdaa1a8471811336cc # [osx and arm64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-common-static-{{ version }}-amd64.tgz # [linux and x86_64]
    sha256: e3a02eaa6e28f47ae72f34850e767d91c92dc286212d0bb099bffd9072118f97 # [linux and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-common-static-{{ version }}-arm64.tgz # [linux and aarch64]
    sha256: f958981073e6d46eec07d9494223334bc37dfccad846f1ce1612cf8f299362c0 # [linux and aarch64]

build:
  number: 0
  binary_relocation: False

test:
  commands:
    - clickhouse client --version

about:
  home: https://clickhouse.com/
  license: Apache 2.0
  summary: ClickHouse® is a free analytics DBMS for big data
  description: |
    ClickHouse® is an open-source column-oriented database management system
    that allows generating analytical data reports in real-time.
  doc_url: https://clickhouse.com/docs
  dev_url: https://github.com/ClickHouse/ClickHouse
