{% set name = "clickhouse" %}
{% set version = "24.6.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.memfault1

source:
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos # [osx and x86_64]
    sha256: 7e7502767f81ae5acb112991db7b7abc121df027e45f34decaa5e2cd99e814f7 # [osx and x86_64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-macos-aarch64 # [osx and arm64]
    sha256: 2ac1ad4b2a66c84634f569368d40bb26a1c1c5b5d252bb8f827a8acf7203d889 # [osx and arm64]
  - url: https://github.com/ClickHouse/ClickHouse/releases/download/v{{ version }}-stable/clickhouse-common-static-{{ version }}-amd64.tgz # [linux64]
    sha256: 1628abfe7275488d3b7b192d8ddba2872d470077d6f4fca884a0941509e57867 # [linux64]

build:
  number: 0
  binary_relocation: False

test:
  commands:
    - clickhouse client --version

about:
  home: https://clickhouse.com/
  license: Apache 2.0
  summary: ClickHouse® is a free analytics DBMS for big data
  description: |
    ClickHouse® is an open-source column-oriented database management system
    that allows generating analytical data reports in real-time.
  doc_url: https://clickhouse.com/docs
  dev_url: https://github.com/ClickHouse/ClickHouse
