{% set version = "13.3.1-1.1" %}

package:
  name: xpack-gcc-arm-none-eabi
  # conda package versions do not permit hyphens, replace with '.'
  version: {{ version|replace('-', '.') }}

source:
  # (_VER=13.3.1-1.1; for _arch in darwin-x64 darwin-arm64 linux-x64 linux-arm64 win32-x64; do curl -sSL https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v${_VER}/xpack-arm-none-eabi-gcc-${_VER}-${_arch}.tar.gz | sha256sum; done)

  - url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v{{ version }}/xpack-arm-none-eabi-gcc-{{ version }}-darwin-x64.tar.gz # [osx and x86_64]
    sha256: afd69764478275ee3e5b9a12d61250ae348a79a4d1fa767e5fa2762ae8b77b2a # [osx and x86_64]

  - url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v{{ version }}/xpack-arm-none-eabi-gcc-{{ version }}-darwin-arm64.tar.gz # [osx and arm64]
    sha256: e37c379cbc423353902aada84b2b4d5a9316c2c8746c9608e69c8ac23e654aa3 # [osx and arm64]

  - url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v{{ version }}/xpack-arm-none-eabi-gcc-{{ version }}-linux-x64.tar.gz # [linux64]
    sha256: 006c89337eced277fdf4c1c3bf3aebe55c85e8d52cba8d412009717fb781b959 # [linux64]

  - url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v{{ version }}/xpack-arm-none-eabi-gcc-{{ version }}-linux-arm64.tar.gz # [linux and aarch64]
    sha256: 34fa25d7dcd57bfdd3aeff5c595eac20dbf21a2d84b72e6c2db3bc67d556a1af # [linux and aarch64]

  - url: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v{{ version }}/xpack-arm-none-eabi-gcc-{{ version }}-win32-x64.zip # [win]
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5 # [win]

build:
  string: '0'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack
  license: MIT
  summary: The xPack GNU Arm Embedded GCC
