{% set version = "1.11.0" %}

package:
  name: libssh2-split
  version: {{ version }}.memfault0

source:
  url: https://www.libssh2.org/download/libssh2-{{ version }}.tar.gz
  sha256: 3736161e41e2693324deb38c26cfdc3efe6209d634ba4258db1cecff6a5ad461

build:
  number: 0

outputs:
  - name: libssh2
    script: build_shared.sh  # [unix]
    build:
      run_exports:
        - {{ pin_subpackage('libssh2') }}
    requirements:
      build:
        # This breals a dependency cycle on unix
        # curl->libssh2->cmake->curl
        - cmake-no-system  # [not win]
        - {{ compiler('c') }}   # [not (osx and arm64)]
        - {{ compiler('clang_bootstrap') }} 11.*  # [osx and arm64]
        - cctools_{{ target_platform }}  # [osx and arm64]
        - make   # [unix]
      host:
        - openssl
        - zlib
    test:
      commands:
        - test -f $PREFIX/include/libssh2.h              # [not win]
        - test -f $PREFIX/include/libssh2_publickey.h    # [not win]
        - test -f $PREFIX/include/libssh2_sftp.h         # [not win]

        - test ! -f $PREFIX/lib/libssh2.a          # [not win]
        - test -f $PREFIX/lib/libssh2${SHLIB_EXT}  # [not win]

about:
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library

  description: |
    libssh2 is a library implementing the SSH2 protocol, available under the revised BSD license.
  dev_url: https://github.com/libssh2/libssh2
