{% set name = "ecs-cli" %}
{% set version = "1.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault0

source:
  url: https://github.com/memfault/memfault-ecs-cli/releases/download/{{ version }}/ecs-cli.darwin-amd64 # [osx]
  sha256: d1cfdb47a22bb940166c2bf03ff451fa4e450bad25d0c9d8d4e2828bed01a791 # [osx]
  url: https://github.com/memfault/memfault-ecs-cli/releases/download/{{ version }}/ecs-cli.linux-amd64 # [linux64]
  sha256: 0409d1bfe6fc5afdebae5846b1eb347df8554324e14ec0919060355657704c21 # [linux64]
  fn: ecs-cli

build:
  string: '0'

test:
  commands:
    - ecs-cli --version

about:
  home: https://github.com/memfault/memfault-ecs-cli
