{% set name = "ecs-cli" %}
{% set version = "1.21.0" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault2

source:
  url: https://github.com/memfault/memfault-ecs-cli/releases/download/{{ version }}.memfault2/ecs-cli.darwin-amd64 # [osx]
  sha256: 44cc90ceaaa792547380781747ab999b2dd3c9fb36a755d9ac5e3b468ab73326 # [osx]
  url: https://github.com/memfault/memfault-ecs-cli/releases/download/{{ version }}.memfault2/ecs-cli.linux-amd64 # [linux and x86_64]
  sha256: d272eb81279f834e6c205eec0dda0a581c8982b02cbc9e0b0493ca2bbb93dd6a # [linux and x86_64]
  url: https://github.com/memfault/memfault-ecs-cli/releases/download/{{ version }}.memfault2/ecs-cli.linux-arm64 # [linux and aarch64]
  sha256: d84fa6db6017351725f6545797281835d4388668b120998146aa9190006271c5 # [linux and aarch64]
  fn: ecs-cli

build:
  string: '0'

test:
  commands:
    - ecs-cli --version

about:
  home: https://github.com/memfault/memfault-ecs-cli
