{% set name = "gitleaks" %}
{% set version = "8.30.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # get the checksums from the checksum file, included in the release
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_darwin_x64.tar.gz # [osx and x86_64]
  sha256: dfe101a4db2255fc85120ac7f3d25e4342c3c20cf749f2c20a18081af1952709 # [osx and x86_64]
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_darwin_arm64.tar.gz # [osx and arm64]
  sha256: b40ab0ae55c505963e365f271a8d3846efbc170aa17f2607f13df610a9aeb6a5 # [osx and arm64]
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_linux_x64.tar.gz # [linux64]
  sha256: 551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb # [linux64]

build:
  string: '1'
  binary_relocation: False

test:
  commands:
    - gitleaks version

about:
  home: https://github.com/zricethezav/gitleaks
  license: MIT
  summary: Scan git repos (or files) for secrets using regex and entropy key
