{% set name = "gitleaks" %}
{% set version = "8.18.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # get the checksums from the checksum file, included in the release
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_darwin_x64.tar.gz # [osx and x86_64]
  sha256: 1a69e5666b13cd374889cbcb1939ed1573b63b551251283d5d2329a53cf58e2f # [osx and x86_64]
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_darwin_arm64.tar.gz # [osx and arm64]
  sha256: a480d8593acd8215b22402cf0f3f88b01dcd3610c63b5391db640f7767e62104 # [osx and arm64]
  url: https://github.com/zricethezav/gitleaks/releases/download/v{{ version }}/gitleaks_{{ version }}_linux_x64.tar.gz # [linux64]
  sha256: ba6dbb656933921c775ee5a2d1c13a91046e7952e9d919f9bac4cec61d628e7d # [linux64]

build:
  string: '1'
  binary_relocation: False

test:
  commands:
    - gitleaks version

about:
  home: https://github.com/zricethezav/gitleaks
  license: MIT
  summary: Scan git repos (or files) for secrets using regex and entropy key
