{% set name = "xtensa-esp32-elf-gdb" %}
{% set version = "16.2_20250324" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault1

source:
  - url: https://raw.githubusercontent.com/espressif/binutils-gdb/refs/tags/esp-gdb-v{{ version }}/COPYING
  - url: https://github.com/espressif/binutils-gdb/releases/download/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-aarch64-apple-darwin21.1.tar.gz # [osx and arm64]
    sha256: b6d85c0d76d653bb55f9d06b0cd509eab7e99db541c88b8c849c64827e9d74a9 # [osx and arm64]
  - url: https://github.com/espressif/binutils-gdb/releases/download/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-x86_64-apple-darwin21.1.tar.gz # [osx and x86_64]
    sha256: 398c429cfe696bad01d636c5488cadc87b20471c1b5ed02c60eee5ef2a775c93 # [osx and x86_64]
  - url: https://github.com/espressif/binutils-gdb/releases/download/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-x86_64-linux-gnu.tar.gz # [linux]
    sha256: 27b58ab12248e04277c4fdc74038cf0a001d5142df091ab94939ad35053738fd # [linux]

  - path: xtensa-lx106-elf-gdb

build:
  number: '0'
  skip: True  # [win]

requirements:
  host:
    - python {{ python }}
    - texinfo
    - ncurses
    - xz
    - zlib {{ zlib }}
    - libiconv
    - mpfr
    - gmp
    - expat
    # For libdebuginfod:
    - elfutils
  run:
    - python {{ python }}
    - ncurses
    - xz
    - zlib  {{ zlib }}
    - libiconv
    - mpfr
    - gmp
    - expat
    # For libdebuginfod:
    - elfutils

test:
  commands:
    # test the wrappers which call the actual xtensa-esp-elf-gdb bin
    - xtensa-esp32-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s2-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s3-elf-gdb -ex "print 1" --batch
    - xtensa-lx106-elf-gdb -ex "print 1" --batch

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: git://sourceware.org/git/binutils-gdb.git

extra:
  recipe-url: https://github.com/memfault/conda-recipes/tree/master/gdb-xtensa-esp32-elf
