{% set name = "xtensa-esp32-elf-gdb" %}
{% set version = "12.1_20221002" %}
{% set url = "https://github.com/espressif/binutils-gdb/releases/download" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault2

source:
  url: {{ url }}/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-x86_64-apple-darwin14.tar.gz # [osx and x86_64]
  sha256: 417fcf8d1b596b9481603d6987def1d6cfcebdb9739f53940887334a7de855fa # [osx and x86_64]
  url: {{ url }}/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-aarch64-apple-darwin21.1.tar.gz # [osx and arm64]
  sha256: 95d6ed2311d6a72bf349e152d096aeeb151f9c5989bfa3120facb1c99e879196 # [osx and arm64]
  url: {{ url }}/esp-gdb-v{{ version }}/xtensa-esp-elf-gdb-{{ version }}-x86_64-linux-gnu.tar.gz # [linux64]
  sha256: d056f2435ef05cccadac5d8fcefa3efd8f8c456c3d853f5eba1edb501acfe4f7 # [linux64]

build:
  number: '0'
  skip: True  # [win]

test:
  commands:
    # test the wrapper scripts, which call the actual xtensa-esp-elf-gdb bin
    - xtensa-esp32-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s2-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s3-elf-gdb -ex "print 1" --batch

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-2.0
  license_family: GPL
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: git://sourceware.org/git/binutils-gdb.git

extra:
  recipe-url: https://github.com/memfault/conda-recipes/tree/master/gdb-xtensa-esp32-elf
