{% set name = "xtensa-esp32-elf-gdb" %}
{% set version = "11.1_20220318" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault2

source:
  # annoying workaround for conda-build not handling the relative submodule ref
  # correctly
  # - git_url: https://github.com/espressif/binutils-gdb.git
  - git_url: https://github.com/noahp/espressif-binutils-gdb.git
    git_rev: esp-gdb-v{{ version }}-memfault0

  # wrapper scripts for esp32 variants
  - path: xtensa-esp32-elf-gdb
  - path: xtensa-esp32s2-elf-gdb
  - path: xtensa-esp32s3-elf-gdb

build:
  number: '0'
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - bison # [linux]
  host:
    - python {{ python }}
    - texinfo
    - ncurses {{ ncurses }}
    - xz {{ xz }}
    - zlib {{ zlib }}
    - libiconv {{ libiconv }}
    - mpfr {{ mpfr }}
    - gmp {{ gmp }}
    - expat {{ expat }}
  run:
    - python {{ python }}
    - ncurses {{ ncurses }}
    - xz {{ xz }}
    - zlib {{ zlib }}
    - libiconv {{ libiconv }}
    - mpfr {{ mpfr }}
    - gmp {{ gmp }}
    - expat {{ expat }}

test:
  commands:
    # test the wrapper scripts, which call the actual xtensa-esp-elf-gdb bin
    - xtensa-esp32-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s2-elf-gdb -ex "print 1" --batch
    - xtensa-esp32s3-elf-gdb -ex "print 1" --batch

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: git://sourceware.org/git/binutils-gdb.git

extra:
  recipe-url: https://github.com/memfault/conda-recipes/tree/master/gdb-xtensa-esp32-elf
