{% set name = "overmind" %}
{% set version = "2.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # > (OVERMIND_VER=2.5.1; for _arch in macos-amd64 macos-arm64 linux-amd64; do curl -sSL https://github.com/DarthSim/overmind/releases/download/v${OVERMIND_VER}/overmind-v${OVERMIND_VER}-${_arch}.gz | sha256sum; done)
  url: https://github.com/DarthSim/overmind/releases/download/v{{ version }}/overmind-v{{ version}}-macos-amd64.gz    # [osx and x86_64]
  sha256: 58cc613d08bcb9b6c92b8b70e815d5dbb2ab9a30cfa6aa295ea796dc46ef1361                                            # [osx and x86_64]
  url: https://github.com/DarthSim/overmind/releases/download/v{{ version }}/overmind-v{{ version }}-macos-arm64.gz   # [osx and arm64]
  sha256: 04aa1dcf64b3d0272b51f49fd300ee346d0bd96e5cfc245121c8d56f2ffaac97                                            # [osx and arm64]
  url: https://github.com/DarthSim/overmind/releases/download/v{{ version }}/overmind-v{{ version }}-linux-amd64.gz   # [linux and x86_64]
  sha256: a17159b8e97d13f3679a4e8fbc9d4747f82d5af9f6d32597b72821378b5d0b6f                                            # [linux and x86_64]
  url: https://github.com/DarthSim/overmind/releases/download/v{{ version }}/overmind-v{{ version }}-linux-arm64.gz   # [linux and aarch64]
  sha256: 42cb6d79c8adcf4c68dfb2ddf09e63a0803b023af5b17d42e05ccbfa4b86bee2                                            # [linux and aarch64]

build:
  string: '1'
  binary_relocation: False

requirements:
  run:
    - tmux >=3.6

test:
  commands:
    - overmind --version

about:
  home: https://github.com/DarthSim/overmind
  license: MIT
  summary: Overmind is a process manager for Procfile-based applications and tmux.
