{% set name = "nghttp2" %}
{% set version = "1.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.memfault

source:
  url: https://github.com/nghttp2/{{ name }}/releases/download/v{{ version }}/nghttp2-{{ version }}.tar.gz
  sha256: 482e41a46381d10adbdfdd44c1942ed5fd1a419e0ab6f4a5ff5b61468fe6f00d

build:
  number: 0

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make        # [unix]
    - pkg-config  # [unix]
  host:
    - zlib            # [unix]
    - openssl         # [unix]
    # Use one dependency without any constraints to help the
    # libev migrator set the right global pinning
    - libev           # [unix]
    - libev >=4.11    # [unix]
    # Use one dependency without any constraints to help the
    # c-ares migrator set the right global pinning
    - c-ares          # [unix]
    - c-ares >=1.7.5  # [unix]
  run:
    - libstdcxx-ng  # [linux]


outputs:
  - name: libnghttp2
    script: install.sh  # [unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make        # [unix]
        - pkg-config  # [unix]
      host:
        - zlib            # [unix]
        - openssl         # [unix]
        # Use one dependency without any constraints to help the
        # libev migrator set the right global pinning
        - libev           # [unix]
        - libev >=4.11    # [unix]
        # Use one dependency without any constraints to help the
        # c-ares migrator set the right global pinning
        - c-ares          # [unix]
        - c-ares >=1.7.5  # [unix]
      run:
        - libstdcxx-ng  # [linux]
        # https://github.com/conda-forge/libev-feedstock/pull/14
        - {{ pin_compatible('libev') }}  # [unix]
    build:
      run_exports:
        - {{ pin_subpackage('libnghttp2') }}
    files:                           # [unix]
      - include/nghttp2/nghttp2*     # [unix]
      - lib/libnghttp2*              # [unix]
      - lib/nghttp2*                 # [unix]
      - lib/pkgconfig/libnghttp2*    # [unix]
      - bin/nghttp*                  # [unix]
    test:
      commands:
        # The binary command requires libev which we don't have on conda-forge
        # on windows
        - nghttp -nv https://nghttp2.org             # [unix]
        - test ! -f ${PREFIX}/lib/lib{{ name }}.a    # [unix]
        - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.

  description: |
    This is an implementation of the Hypertext Transfer Protocol version 2 in C.

    The framing layer of HTTP/2 is implemented as a reusable C library. On top
    of that, we have implemented an HTTP/2 client, server and proxy. We have
    also developed load test and benchmarking tools for HTTP/2.
  doc_url: https://nghttp2.org/documentation/
  dev_url: https://github.com/nghttp2/nghttp2
