{% set name = "cpputest" %}
{% set version = "4.0" %}

package:
  name: {{ name }}
  version: {{ version }}.memfault0

source:
  url: https://github.com/cpputest/cpputest/releases/download/v{{ version }}/cpputest-{{ version }}.tar.gz
  sha256: 21c692105db15299b5529af81a11a7ad80397f92c122bd7bf1e4a4b0e85654f7

  patches:
    # as of v4.0, cpputest's config.sub needs patching to build on osx-arm64
    - 0001-Re-run-autogen.sh.patch

build:
  number: "0"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
test:
  commands:
    - test -f ${PREFIX}/lib/libCppUTest.a

about:
  home: http://cpputest.github.io/
  dev_url: https://github.com/cpputest/cpputest
  doc_url: http://cpputest.github.io/manual.html
  license: BSD-3-Clause
  license_file: COPYING
  summary: CppUTest is a C /C++ based unit xUnit test framework for unit testing and for test-driving your code.
