{% set name = "aws-vault" %}
{% set version = "6.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-darwin-amd64.dmg # [osx and x86_64]
  sha256: eeb7b8dbdba7bb18fcf32e1c422683d5fd444c6c3b5eb41e760bbfcb2036df6c # [osx and x86_64]
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-darwin-arm64.dmg # [osx and arm64]
  sha256: 7c624f16a60f6d48900d7aa7f17add991376f1d280e8a5168094e19098797c35 # [osx and arm64]
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-linux-amd64 # [linux64 and x86_64]
  sha256: f4571f90a4847ea42c239ebbef058d18baccfe9f28092ace84f348c7cd29aa19 # [linux64 and x86_64]

build:
  string: '1'
  binary_relocation: False

test:
  commands:
    - aws-vault --version

about:
  home: https://github.com/99designs/aws-vault
  license: MIT
  summary: AWS Vault is a tool to securely store and access AWS credentials in a development environment
