{% set name = "aws-vault" %}
{% set version = "7.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-darwin-amd64.dmg # [osx and x86_64]
  sha256: c0642de33329eb6eade70532f0c9eb769d2a1b52dfa56b63196ef51c7dea6445 # [osx and x86_64]
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-darwin-arm64.dmg # [osx and arm64]
  sha256: 9887eb8f6c2bd431e814b32b9ec8a6bd394dbeb0c60822d76ed9be3c84ca1cc5 # [osx and arm64]
  url: https://github.com/99designs/aws-vault/releases/download/v{{ version }}/aws-vault-linux-amd64 # [linux64 and x86_64]
  sha256: b92bcfc4a78aa8c547ae5920d196943268529c5dbc9c5aca80b797a18a5d0693 # [linux64 and x86_64]

build:
  string: '1'
  binary_relocation: False

test:
  commands:
    - aws-vault --version

about:
  home: https://github.com/99designs/aws-vault
  license: MIT
  summary: AWS Vault is a tool to securely store and access AWS credentials in a development environment
