{% set name = "circleci-cli" %}
{% set version = "0.1.20397" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/CircleCI-Public/circleci-cli/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b4dbf610860d8acd5f8a85a8b5f7b530392fc32121805a42276c4c715ccbb453

build:
  string: '0'
  binary_relocation: False
  detect_binary_files_with_prefix: False

requirements:
  build:
    - go-nocgo=1.18.3

test:
  commands:
    - circleci version

about:
  home: https://github.com/CircleCI-Public/circleci-cli
  license: MIT
  summary: Use CircleCI from the command line
