{% set name = "memfault-config" %}
{% set version = "1.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: '0'
  skip: True  # [win]
  noarch: generic

test:
  commands:
    - test "$MEMFAULT_DEPS_ROOT"
    - test "$PYTHON_KEYRING_BACKEND"

about:
  home: https://memfault.com
  summary: A simple recipe to configure items for Memfault internal usage
