{% set version = "0.191" %}

package:
  name: elfutils
  version: {{ version }}.memfault0

source:
  fn: elfutils-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/elfutils-{{ version }}.tar.bz2
  sha256: df76db71366d1d708365fc7a6c60ca48398f14367eb2b8954efc8897147ad871

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - pkg-config  # [linux]
    - make  # [linux]
  host:
    - bzip2  # [linux]
    - libarchive  # [linux]
    - libcurl  # [linux]
    - libmicrohttpd  # [linux]
    - m4  # [linux]
    - sqlite  # [linux]
    - xz  # [linux]
    - zlib  # [linux]
    - zstd  # [linux]

test:
# Currently disabled
#   requires:
#     - {{ compiler('c') }}
#     - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
  memfault-recipe-repo:
    - https://github.com/memfault/conda-recipes/tree/master/elfutils
